In [3]:
import numpy as np
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)
], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float)

In [5]:
np.zeros((3,4))
np.ones((2,3,4),dtype=np.int16)
d = np.arange(10,25,5)
np.linspace(0,2,9)
e = np.full((2,2),7)
f = np.eye(2)
np.random.random((2,2))
np.empty((3,2))

array([[1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309]])

In [7]:
np.save('my-array', a)
np.savez('array.npz', a, b)
np.load('my-array.npy')

array([1, 2, 3])

In [11]:
np.loadtxt("my-file.txt")
np.genfromtxt("my-file.csv", delimiter=',')
np.savetxt('ny-array.txt' , a, delimiter='' )

FileNotFoundError: my-file.txt not found.

In [12]:
 np.info(np.ndarray.dtype)

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [13]:
a.shape
len(a)
b.ndim
e.size
b.dtype
b.dtype.name
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np.int64
np.float32
np.complex
np.bool
np.object
np.string_
np.unicode_ 


C:\Users\STUDENT\AppData\Local\Temp\ipykernel_3136\3953837166.py:3: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.complex
C:\Users\STUDENT\AppData\Local\Temp\ipykernel_3136\3953837166.py:4: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool
C:\Users\STUDENT\AppData\Local\Temp\ipykernel_3136\3953837166.py:5: DeprecationWarning: `

numpy.str_

In [27]:
g = a-b 
array([[-0.5,0. ,0.],
       [-3. , 3. , 3.]])
np.subtract(a,b)
b+a 
array([[ 2.5, 4. , 6.],[5. ,7. ,9. ]])
np.add(b,a)
a/b 
array([[0.66666667,1. ,1.],[0.25 ,0.4 ,0.5 ]])
np.divide(a,b)
a*b 
array([[1.5, 4. ,9.],[ 4. , 10. , 18. ]])
np.multiply(a,b)
np.exp(b)
np.sqrt(b)
np.sin(a)
np.cos(b)
np.log(a)
e.dot(f)
array([[7.,7.],[7.,7.]]) 

NameError: name 'array' is not defined

In [28]:
 a == b
 array([[false,True,True],[false,False,False ]], dtype=bool)
a<2
 array([True,False,False], dtype=bool)
np.array_equal(a, b) 

NameError: name 'array' is not defined

In [29]:
a.sum()
a.min()
b.max(axis=0)
b.cumsum(axis=1)
a.mean()
np.median(b)
np.corrcoef(a)
np.std(b) 

1.5920810978785667

In [30]:
h = a.view()
np.copy(a)
h = a.copy()

In [31]:
a.sort()
c.sort(axis=0)

In [4]:
b[[1,0,1, 0],[0,1, 2, 0]]
 array([ 4.1, 2.5, 6.3,1.5])
b[[1,0,1, 0]][:,[0,1,2,0]]
 array([[ 4. ,5. , 6. , 4.],[1.5, 2. , 3. ,1.5],[ 4. ,5. , 6. , 4.],[1.5, 2. , 3. ,1.5]])

IndentationError: unexpected indent (3412979287.py, line 2)

In [9]:
a=2
a[a<2]
array([1])

TypeError: 'int' object is not subscriptable